"use client";
import {useEffect,useState} from "react";
import {ArrowDownLeft,ArrowUpRight,Bell,CalendarDays,CheckCircle2,ChevronRight,Download,HeartHandshake,Home,Landmark,Menu,MoreHorizontal,Plus,ReceiptText,Search,Settings,ShieldCheck,Trash2,Users,Wallet,X} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Progress} from "@/components/ui/progress";

type View="beranda"|"keuangan"|"program"|"kegiatan"|"jamaah";
type Kind="transaction"|"program"|"event"|"member";
type DataRecord={id:number;kind:Kind;title:string;date:string;amount:number;type:string;category:string;details:string;target:number;phone:string;address:string};
const money=(n:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
const nav=[["beranda","Beranda",Home],["keuangan","Keuangan",Wallet],["program","Program Donasi",HeartHandshake],["kegiatan","Kegiatan",CalendarDays],["jamaah","Data Jamaah",Users]] as const;
const trx=[["Infak Jumat","13 Sep 2026",4750000,true],["Pembayaran listrik","12 Sep 2026",1285000,false],["Donasi renovasi","11 Sep 2026",2500000,true],["Konsumsi kajian","10 Sep 2026",875000,false]] as const;
const programs=[{name:"Renovasi Tempat Wudu",raised:38750000,target:60000000,donors:86,color:"emerald",icon:Landmark},{name:"Santunan Yatim",raised:14200000,target:20000000,donors:47,color:"amber",icon:Users},{name:"Operasional Masjid",raised:8450000,target:15000000,donors:31,color:"blue",icon:ReceiptText}];
const events=[["18","SEP","Kajian Ba'da Magrib","Ustaz Ahmad Fauzan · Aula utama","Kajian"],["20","SEP","Jumat Berkah","Pukul 10.00 · Dapur masjid","Sosial"],["22","SEP","TPQ Anak","Pukul 15.30 · Ruang TPQ","Pendidikan"]] as const;

export default function Page(){
 const [view,setView]=useState<View>("beranda"),[open,setOpen]=useState(false),[donate,setDonate]=useState(false),[amount,setAmount]=useState(100000),[done,setDone]=useState(false),[role,setRole]=useState("Pengurus"),[records,setRecords]=useState<DataRecord[]>([]),[form,setForm]=useState<Kind|null>(null);
 useEffect(()=>{try{setRecords(JSON.parse(localStorage.getItem("baitul-fadli-records")||"[]"))}catch{setRecords([])}},[]);
 async function save(data:Omit<DataRecord,"id">){const record={...data,id:Date.now()};setRecords(x=>{const next=[record,...x];localStorage.setItem("baitul-fadli-records",JSON.stringify(next));return next});setForm(null)}
 async function remove(id:number){if(!confirm("Hapus data ini?"))return;setRecords(x=>{const next=x.filter(r=>r.id!==id);localStorage.setItem("baitul-fadli-records",JSON.stringify(next));return next})}
 const title=nav.find(n=>n[0]===view)?.[1];
 return <div className="shell">
  <aside className={"sidebar "+(open?"open":"")}><button className="close" onClick={()=>setOpen(false)}><X/></button>
   <div className="brand"><span><Landmark/></span><div><strong>Masjid Baitul Fadi</strong><small>Pusat Layanan Jamaah</small></div></div>
   <p className="caption">MENU UTAMA</p><nav>{nav.map(([id,label,Icon])=><button key={id} className={view===id?"active":""} onClick={()=>{setView(id);setOpen(false)}}><Icon/>{label}{id==="program"&&<b>3</b>}</button>)}</nav>
   <div className="sidebar-foot"><button><Settings/>Pengaturan</button><section><ShieldCheck/><strong>Data masjid aman</strong><small>Ringkasan hanya dapat diubah oleh pengurus.</small></section></div>
  </aside>{open&&<button className="overlay" onClick={()=>setOpen(false)}/>}
  <main><header><div className="heading"><button className="hamb" onClick={()=>setOpen(true)}><Menu/></button><div><small>14 September 2026</small><h1>{title}</h1></div></div><div className="tools"><label><Search/><input placeholder="Cari data..."/></label><button className="bell"><Bell/><i/></button><select value={role} onChange={e=>setRole(e.target.value)}><option>Pengurus</option><option>Jamaah</option><option>Donatur</option></select><span className="avatar">CB</span></div></header>
   <div className="page">{view==="beranda"?<Dashboard go={setView} donate={()=>setDonate(true)}/>:view==="keuangan"?<Finance records={records} add={()=>setForm("transaction")} remove={remove}/>:view==="program"?<Programs records={records} add={()=>setForm("program")} donate={()=>setDonate(true)} remove={remove}/>:view==="kegiatan"?<Events records={records} add={()=>setForm("event")} remove={remove}/>:<Members records={records} add={()=>setForm("member")} remove={remove}/>}</div>
  </main>
  {form&&<EntryForm kind={form} close={()=>setForm(null)} save={save}/>}
  {donate&&<div className="modal-wrap"><button className="backdrop" onClick={()=>{setDonate(false);setDone(false)}}/><section className="modal"><button className="modal-x" onClick={()=>setDonate(false)}><X/></button>{done?<div className="success"><span><CheckCircle2/></span><h2>Jazakumullahu khairan</h2><p>Niat donasi Anda sudah dicatat. Silakan lanjutkan transfer ke rekening masjid.</p><div>BSI · 7123 4567 890<strong>{money(amount)}</strong></div><Button onClick={()=>setDonate(false)}>Selesai</Button></div>:<><p className="eyebrow">DONASI MASJID</p><h2>Mulai kebaikan hari ini</h2><p>Pilih nominal donasi. Petunjuk transfer tampil setelah Anda melanjutkan.</p><div className="amounts">{[50000,100000,250000,500000].map(n=><button className={amount===n?"chosen":""} onClick={()=>setAmount(n)} key={n}>{money(n)}</button>)}</div><label className="field">Nominal lainnya<div>Rp<input type="number" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></div></label><label className="field">Pilih program<select><option>Renovasi Tempat Wudu</option><option>Santunan Yatim</option><option>Operasional Masjid</option></select></label><Button className="primary" onClick={()=>setDone(true)}>Lanjutkan Donasi <ChevronRight/></Button></>}</section></div>}
 </div>
}

function Dashboard({go,donate}:{go:(v:View)=>void;donate:()=>void}){return <><section className="welcome"><div><p className="eyebrow">ASSALAMUALAIKUM</p><h2>Semoga hari ini penuh keberkahan.</h2><p>Ringkasan pengelolaan Masjid Baitul Fadi bulan September.</p></div><Button onClick={donate}><HeartHandshake/>Donasi Sekarang</Button></section><div className="stats"><Stat l="Saldo Kas" v={money(57725000)} n="Posisi per hari ini" icon={<Wallet/>} c="green"/><Stat l="Pemasukan Bulan Ini" v={money(86450000)} n="Naik 12,4% dari Agustus" icon={<ArrowDownLeft/>} c="blue"/><Stat l="Pengeluaran Bulan Ini" v={money(28725000)} n="33,2% dari pemasukan" icon={<ArrowUpRight/>} c="gold"/><Stat l="Jamaah Terdaftar" v="428" n="12 jamaah baru bulan ini" icon={<Users/>} c="navy"/></div><div className="dashboard-grid"><Panel t="Transaksi Terbaru" a="Lihat laporan" click={()=>go("keuangan")}><TransactionList/></Panel><Panel t="Program Berjalan" a="Lihat semua" click={()=>go("program")}><div className="mini-programs">{programs.slice(0,2).map(p=><ProgramLine key={p.name} p={p}/>)}</div></Panel><Panel t="Agenda Terdekat" a="Kalender" click={()=>go("kegiatan")}><EventList/></Panel><section className="quote"><b>“</b><p>Perumpamaan orang yang menginfakkan hartanya di jalan Allah seperti sebutir biji yang menumbuhkan tujuh tangkai.</p><small>QS. Al-Baqarah: 261</small></section></div></>}
function Stat({l,v,n,icon,c}:{l:string;v:string;n:string;icon:React.ReactNode;c:string}){return <article className="stat"><span className={"stat-icon "+c}>{icon}</span><small>{l}</small><strong>{v}</strong><em>{n}</em></article>}
function Panel({t,a,click,children}:{t:string;a:string;click?:()=>void;children:React.ReactNode}){return <section className="panel"><div className="panel-head"><h3>{t}</h3><button onClick={click}>{a}<ChevronRight/></button></div>{children}</section>}
function TransactionList(){return <div>{trx.map(([n,d,v,isIn])=><div className="transaction" key={n}><span className={isIn?"in":"out"}>{isIn?<ArrowDownLeft/>:<ArrowUpRight/>}</span><div><strong>{n}</strong><small>{d}</small></div><b className={isIn?"plus":"minus"}>{isIn?"+":"−"}{money(v)}</b></div>)}</div>}
function ProgramLine({p}:{p:typeof programs[number]}){const pct=Math.round(p.raised/p.target*100);return <div><div className="program-line"><strong>{p.name}</strong><span>{pct}%</span></div><Progress value={pct}/><small>{money(p.raised)} dari {money(p.target)}</small></div>}
function EventList(){return <div>{events.map(([day,mon,n,d,tag])=><div className="event-row" key={n}><span className="date"><b>{day}</b><small>{mon}</small></span><div><strong>{n}</strong><small>{d}</small></div><em>{tag}</em></div>)}</div>}
function Intro({k,t,p,children}:{k:string;t:string;p:string;children?:React.ReactNode}){return <div className="intro"><div><p className="eyebrow">{k}</p><h2>{t}</h2><p>{p}</p></div>{children}</div>}

function Finance({records,add,remove}:{records:DataRecord[];add:()=>void;remove:(id:number)=>void}){const own=records.filter(r=>r.kind==="transaction");return <div className="stack"><Intro k="TRANSPARAN & AKUNTABEL" t="Laporan Keuangan Masjid" p="Pantau arus dana masjid dengan ringkas dan mudah dipahami."><div className="actions"><Button variant="outline"><Download/>Unduh Laporan</Button><Button className="primary" onClick={add}><Plus/>Catat Transaksi</Button></div></Intro><div className="stats three"><Stat l="Total Pemasukan" v={money(own.filter(r=>r.type==="Pemasukan").reduce((a,r)=>a+r.amount,0))} n="Data yang diinput" icon={<ArrowDownLeft/>} c="green"/><Stat l="Total Pengeluaran" v={money(own.filter(r=>r.type==="Pengeluaran").reduce((a,r)=>a+r.amount,0))} n="Data yang diinput" icon={<ArrowUpRight/>} c="gold"/><Stat l="Jumlah Transaksi" v={String(own.length)} n="Tersimpan permanen" icon={<Wallet/>} c="navy"/></div><Panel t="Daftar Transaksi" a={own.length+" transaksi"}><div className="table"><div className="tr th"><span>Transaksi</span><span>Tanggal</span><span>Kategori</span><span>Nominal</span><span/></div>{own.map(r=><div className="tr" key={r.id}><span><i className={"dot "+(r.type==="Pemasukan"?"in":"out")}/><strong>{r.title}</strong></span><span>{r.date}</span><span><em>{r.category||"-"}</em></span><b className={r.type==="Pemasukan"?"plus":"minus"}>{r.type==="Pemasukan"?"+":"−"}{money(r.amount)}</b><button onClick={()=>remove(r.id)} aria-label="Hapus"><Trash2/></button></div>)}{!own.length&&<p className="empty">Belum ada transaksi. Klik “Catat Transaksi” untuk mulai.</p>}</div></Panel></div>}
function Programs({records,add,donate,remove}:{records:DataRecord[];add:()=>void;donate:()=>void;remove:(id:number)=>void}){const own=records.filter(r=>r.kind==="program");return <div className="stack"><Intro k="PROGRAM KEBAIKAN" t="Tumbuhkan Manfaat Bersama" p="Setiap rupiah dikelola untuk kebutuhan jamaah dan kemakmuran masjid."><div className="actions"><Button variant="outline" onClick={add}><Plus/>Tambah Program</Button><Button className="gold-btn" onClick={donate}><HeartHandshake/>Donasi Sekarang</Button></div></Intro><div className="program-cards">{own.map((r,i)=>{const pct=r.target?Math.round(r.amount/r.target*100):0;return <article key={r.id}><div className={"program-top "+(["emerald","amber","blue"][i%3])}><span><Landmark/></span><b>{r.category||"Program"}</b></div><div className="program-body"><h3>{r.title}</h3><p>{r.details||"Program kebaikan Masjid Baitul Fadi."}</p><div className="program-line"><strong>{money(r.amount)}</strong><span>{pct}%</span></div><Progress value={pct}/><small>Target {money(r.target)}</small><div className="card-actions"><Button variant="outline" onClick={donate}>Donasi<ChevronRight/></Button><Button variant="outline" onClick={()=>remove(r.id)}><Trash2/></Button></div></div></article>})}{!own.length&&<p className="empty">Belum ada program. Klik “Tambah Program”.</p>}</div></div>}
function Events({records,add,remove}:{records:DataRecord[];add:()=>void;remove:(id:number)=>void}){const own=records.filter(r=>r.kind==="event");return <div className="stack"><Intro k="AGENDA MASJID" t="Hidupkan Masjid, Eratkan Ukhuwah" p="Jadwal ibadah, pendidikan, dan kegiatan sosial untuk seluruh jamaah."><Button className="primary" onClick={add}><Plus/>Tambah Kegiatan</Button></Intro><div className="event-cards">{own.map(r=><article key={r.id}><span className="date large"><small>{r.date.slice(5,7)||"BLN"}</small><b>{r.date.slice(8,10)||"--"}</b></span><div><em>{r.category||"Kegiatan"}</em><h3>{r.title}</h3><p>{r.details}</p></div><button onClick={()=>remove(r.id)}><Trash2/></button></article>)}{!own.length&&<p className="empty">Belum ada kegiatan. Klik “Tambah Kegiatan”.</p>}</div></div>}
function Members({records,add,remove}:{records:DataRecord[];add:()=>void;remove:(id:number)=>void}){const own=records.filter(r=>r.kind==="member");return <div className="stack"><Intro k="DATABASE JAMAAH" t="Jamaah Masjid Baitul Fadi" p="Data jamaah untuk komunikasi kegiatan dan pelayanan yang lebih baik."><Button className="primary" onClick={add}><Plus/>Tambah Jamaah</Button></Intro><div className="stats three"><Stat l="Total Jamaah" v={String(own.length)} n="Data tersimpan" icon={<Users/>} c="green"/><Stat l="Relawan" v={String(own.filter(r=>r.category==="Relawan").length)} n="Siap membantu" icon={<HeartHandshake/>} c="blue"/><Stat l="Kepala Keluarga" v={String(own.filter(r=>r.type==="Kepala Keluarga").length)} n="Terdata" icon={<Home/>} c="gold"/></div><Panel t="Daftar Jamaah" a={own.length+" jamaah"}><div className="members">{own.map(r=><article key={r.id}><span>{r.title.split(" ").map(x=>x[0]).slice(0,2).join("")}</span><div><strong>{r.title}</strong><small>{r.phone||"-"} · {r.address||"-"}</small></div><button onClick={()=>remove(r.id)}><Trash2/></button></article>)}{!own.length&&<p className="empty">Belum ada jamaah. Klik “Tambah Jamaah”.</p>}</div></Panel></div>}

function EntryForm({kind,close,save}:{kind:Kind;close:()=>void;save:(d:Omit<DataRecord,"id">)=>Promise<void>}){
 const [title,setTitle]=useState(""),[date,setDate]=useState(""),[amount,setAmount]=useState(0),[target,setTarget]=useState(0),[type,setType]=useState(kind==="transaction"?"Pemasukan":kind==="member"?"Jamaah":""),[category,setCategory]=useState(""),[details,setDetails]=useState(""),[phone,setPhone]=useState(""),[address,setAddress]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const labels={transaction:"Transaksi",program:"Program Donasi",event:"Kegiatan",member:"Jamaah"};
 async function submit(e:React.FormEvent){e.preventDefault();if(!title)return setError("Nama/judul wajib diisi.");setBusy(true);setError("");try{await save({kind,title,date,amount,type,category,details,target,phone,address})}catch(err){setError(err instanceof Error?err.message:"Gagal menyimpan")}finally{setBusy(false)}}
 return <div className="modal-wrap"><button className="backdrop" onClick={close}/><form className="modal entry-form" onSubmit={submit}><button type="button" className="modal-x" onClick={close}><X/></button><p className="eyebrow">INPUT DATA</p><h2>Tambah {labels[kind]}</h2>
  <label className="field">{kind==="member"?"Nama lengkap":"Nama / judul"}<input value={title} onChange={e=>setTitle(e.target.value)} placeholder={kind==="transaction"?"Contoh: Infak Jumat":kind==="member"?"Nama jamaah":"Tuliskan nama"}/></label>
  {(kind==="transaction"||kind==="event")&&<label className="field">Tanggal<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>}
  {kind==="transaction"&&<><label className="field">Jenis<select value={type} onChange={e=>setType(e.target.value)}><option>Pemasukan</option><option>Pengeluaran</option></select></label><label className="field">Nominal<input type="number" value={amount||""} onChange={e=>setAmount(Number(e.target.value))} placeholder="0"/></label></>}
  {kind==="program"&&<><label className="field">Dana terkumpul<input type="number" value={amount||""} onChange={e=>setAmount(Number(e.target.value))}/></label><label className="field">Target dana<input type="number" value={target||""} onChange={e=>setTarget(Number(e.target.value))}/></label></>}
  {kind==="member"&&<><label className="field">Nomor WhatsApp<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="08xxxxxxxxxx"/></label><label className="field">Alamat / RT<input value={address} onChange={e=>setAddress(e.target.value)} placeholder="RT 01 / RW 02"/></label><label className="field">Status<select value={type} onChange={e=>setType(e.target.value)}><option>Jamaah</option><option>Kepala Keluarga</option></select></label></>}
  <label className="field">Kategori<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Pilih kategori</option>{kind==="transaction"?<><option>Infak</option><option>Operasional</option><option>Sosial</option><option>Pembangunan</option></>:kind==="program"?<><option>Fasilitas</option><option>Sosial</option><option>Operasional</option></>:kind==="event"?<><option>Kajian</option><option>Sosial</option><option>Pendidikan</option></>:<><option>Jamaah</option><option>Relawan</option></>}</select></label>
  {kind!=="member"&&<label className="field">Keterangan<textarea value={details} onChange={e=>setDetails(e.target.value)} placeholder="Tambahkan rincian"/></label>}
  {error&&<p className="form-error">{error}</p>}<Button className="primary" disabled={busy}>{busy?"Menyimpan...":"Simpan Data"}</Button>
 </form></div>
}
